### ISSUE TITLE
Error上报/GET请求出错

### ISSUE THREAD

**Issue by Greygbear** [vannvan/yuque-tools#44]
Node: 20.13.1 OS: win32
错误信息: AxiosError: Request failed with status code 403,https://XXXX.yuque.com/XXX/rf6ydl
Error
    at Object.error (file:///C:/Users/XXXX/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///C:/Users/XXXX/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/request.js:63:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

以上信息可删除路径等隐私信息，但需要保留之后的行数哦~

**Comment by Greygbear** [comment]
更换程序版已解决
