### ISSUE TITLE
Error上报/GET请求出错

### ISSUE THREAD

**Issue by Holinc19** [vannvan/yuque-tools#48]
Node: 18.19.1 OS: win32
错误信息: TypeError [ERR_INVALID_URL]: Invalid URL,XXX.com/api/mine/user_books?user_type=Group
Error
    at Object.error (file:///C:/Users/PC/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///C:/Users/PC/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/request.js:63:17

以上信息可删除路径等隐私信息，但需要保留之后的行数哦~​

**Comment by vannvan** [comment]
根据你的报错信息，应该期望是获取团队知识库，请确认以下三项信息是否正确配置：yuque.config.json
```
{
  "host": "",
  "userName": "",
  "password": ""
}
```

[文档详见👉](https://github.com/vannvan/yuque-tools/blob/main/packages/yuque-tools-cli/README.md#%E4%B8%AD%E7%BA%A7%E7%94%A8%E6%B3%95)

**Comment by Holinc19** [comment]
> 根据你的报错信息，应该期望是获取团队知识库，请确认以下三项信息是否正确配置：yuque.config.json
> 
> ```
> {
>   "host": "",
>   "userName": "",
>   "password": ""
> }
> ```
> 
> [文档详见👉](https://github.com/vannvan/yuque-tools/blob/main/packages/yuque-tools-cli/README.md#%E4%B8%AD%E7%BA%A7%E7%94%A8%E6%B3%95)

已配置了的。不确定是不是语雀有什么权限控制？
