### ISSUE TITLE
Error上报/POST请求出错

### ISSUE THREAD

**Issue by liangyongwang** [vannvan/yuque-tools#50]
Node: 18.17.0 OS: win32
错误信息: AxiosError: Request failed with status code 410,https://www.yuque.com/api/mobile_app/accounts/login?language=zh-cn
Error
    at Object.error (file:///C:/Users/admin/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/dev/log.js:8:27)
    at file:///C:/Users/admin/AppData/Roaming/npm/node_modules/yuque-tools/dist/lib/request.js:34:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

我能确定账号密码是对的 但是登录会报错

**Comment by vva1024** [comment]
+1 遇到同样问题，账号密码都没错 但是显示登录出错，我是mac

**Comment by LoneyAngel** [comment]
+1

**Comment by liangyongwang** [comment]
> +1 遇到同样问题，账号密码都没错 但是显示登录出错，我是mac
看release中打包好的工具 我是windows 可以用
https://github.com/vannvan/rust-explore/releases/download/v1.0.4/ytool-Windows-x86_64.zip

**Comment by liangyongwang** [comment]
> +1

看release中打包好的工具 我是windows 可以用
https://github.com/vannvan/rust-explore/releases/download/v1.0.4/ytool-Windows-x86_64.zip
